[CmdletBinding()]
param(
    [string]$RepositoryRoot = (Split-Path -Parent (Split-Path -Parent $PSScriptRoot))
)

$ErrorActionPreference = 'Stop'

$repository = (Resolve-Path -LiteralPath $RepositoryRoot).Path
$sourceRoot = Join-Path $repository 'src/main/java/thaumcraft'
$legacySourceRoot = Join-Path $repository 'src/main/java_old'
$resourceRoot = Join-Path $repository 'src/main/resources'
$templateRoot = Join-Path $repository 'src/main/templates'
$generatedResourceRoot = Join-Path $repository 'src/generated/resources'
$outputPath = Join-Path $repository 'docs/agent-pipeline/filesystem-map.md'

foreach ($requiredPath in @($sourceRoot, $resourceRoot)) {
    if (-not (Test-Path -LiteralPath $requiredPath -PathType Container)) {
        throw "Required source path does not exist: $requiredPath"
    }
}

function Get-FileCount([string]$path) {
    @(Get-ChildItem -LiteralPath $path -File -Recurse -ErrorAction Stop).Count
}

function Get-ImmediateDirectoryRows([string]$path) {
    Get-ChildItem -LiteralPath $path -Directory |
        Sort-Object Name |
        ForEach-Object {
            "| ``$($_.Name)/`` | $(Get-FileCount $_.FullName) |"
        }
}

$javaRows = Get-ImmediateDirectoryRows $sourceRoot
$commonRows = Get-ImmediateDirectoryRows (Join-Path $sourceRoot 'common')
$assetPath = Join-Path $resourceRoot 'assets/thaumcraft'
$dataPath = Join-Path $resourceRoot 'data/thaumcraft'
$assetCount = Get-FileCount $assetPath
$dataCount = Get-FileCount $dataPath
$assetRows = Get-ImmediateDirectoryRows $assetPath
$dataRows = Get-ImmediateDirectoryRows $dataPath
$legacyCount = if (Test-Path -LiteralPath $legacySourceRoot -PathType Container) { Get-FileCount $legacySourceRoot } else { 0 }
$templateCount = if (Test-Path -LiteralPath $templateRoot -PathType Container) { Get-FileCount $templateRoot } else { 0 }
$generatedResourceCount = if (Test-Path -LiteralPath $generatedResourceRoot -PathType Container) { Get-FileCount $generatedResourceRoot } else { 0 }
$testJavaPath = Join-Path $repository 'src/test/java'
$testResourcePath = Join-Path $repository 'src/test/resources'
$testCount = 0
if (Test-Path -LiteralPath $testJavaPath) { $testCount += Get-FileCount $testJavaPath }
if (Test-Path -LiteralPath $testResourcePath) { $testCount += Get-FileCount $testResourcePath }
$gitCommit = (git -C $repository rev-parse --short HEAD).Trim()
$generatedAt = (Get-Date).ToUniversalTime().ToString('yyyy-MM-dd HH:mm:ss UTC')

$content = @"
# Filesystem Map

> Generated by ``tools/agent-pipeline/Update-FileSystemMap.ps1`` at $generatedAt from commit ``$gitCommit``.

Repository root: ``$(Split-Path -Leaf $repository)`` — Minecraft 1.20.1 Forge port.

## Root and Build Surface

| Path | Role |
|---|---|
| ``build.gradle``, ``settings.gradle``, ``gradle.properties`` | ForgeGradle build, mappings, versions, and dependencies |
| ``gradlew``, ``gradlew.bat``, ``gradle/`` | Gradle wrapper |
| ``README.md`` | upstream project claims and setup notes; not parity evidence |
| ``TODO.md`` | upstream implementation leads; audit against source before acting |
| ``TEXTURETODO.md`` | visual asset backlog |
| ``AGENTS.md`` | parity operating contract |
| ``docs/agent-pipeline/`` | agent workflow, map, and workboard |
| ``tools/agent-pipeline/`` | pipeline maintenance tooling |
| ``src/main/java/`` | compiled 1.20.1 port source |
| ``src/main/java_old/`` | $legacyCount legacy reference files; do not compile or bulk-copy them |
| ``src/main/resources/`` | hand-authored assets, data, metadata, and language content |
| ``src/main/templates/`` | $templateCount build-time metadata templates |
| ``src/generated/resources/`` | $generatedResourceCount generated-resource files |

## Java Source — ``src/main/java/thaumcraft``

| Package | Recursive file count |
|---|---:|
$($javaRows -join [Environment]::NewLine)

``Thaumcraft.java`` is the mod bootstrap. ``api/`` holds cross-system contracts; ``common/`` holds gameplay authority; ``client/`` is presentation-only; ``compat/`` holds integration adapters; ``init/`` owns registrations.

## Gameplay Implementation Seams — ``src/main/java/thaumcraft/common``

| Package | Recursive file count |
|---|---:|
$($commonRows -join [Environment]::NewLine)

## Static Content — ``src/main/resources``

| Path | Recursive file count |
|---|---:|
| ``assets/thaumcraft/`` | $assetCount |
| ``data/thaumcraft/`` | $dataCount |

### Asset Domains — ``assets/thaumcraft``

| Directory | Recursive file count |
|---|---:|
$($assetRows -join [Environment]::NewLine)

### Data Domains — ``data/thaumcraft``

| Directory | Recursive file count |
|---|---:|
$($dataRows -join [Environment]::NewLine)

## Test, Run, and Generated Surfaces

| Path | State / use |
|---|---|
| ``src/test/java``, ``src/test/resources`` | $testCount tracked test-source/resource files |
| ``run/`` | disposable local Forge dev instance, configuration, logs, and test state |
| ``build/`` | disposable Gradle output, generated metadata, remapping intermediates, and JARs |
| ``.gradle/`` | disposable local Gradle cache/state |
| ``src/generated/resources/`` | generated-resource input path declared by the build |

``.gitignore`` excludes ``build/``, ``.gradle/``, ``run/``, IDE output, and Eclipse metadata. Treat those directories as generated/disposable and never use them as source-of-truth implementation files.

## Gradle Entry Points

| Command | Use |
|---|---|
| ``.\\gradlew.bat compileJava`` | Java compile gate |
| ``.\\gradlew.bat test`` | deterministic test suite |
| ``.\\gradlew.bat runGameTestServer`` | Minecraft GameTest validation |
| ``.\\gradlew.bat runServer`` | dedicated-server smoke test |
| ``.\\gradlew.bat runClient`` | client smoke and visual validation |
| ``.\\gradlew.bat runData`` | data-generation validation |
| ``.\\gradlew.bat build`` | package/reobfuscation gate |
"@

Set-Content -LiteralPath $outputPath -Value $content -Encoding utf8
Write-Host "Updated $outputPath"
